title: 'Marsha Blackburn Wants Censorship'
url: https://www.marshawantscensorship.org/
share_title: "Marsha Blackburn is a fake conservative who loves Internet censorship"
share_description: "She’s taken hundreds of thousands from big media companies to sell us out."
fb_share_image: "images/marshablackburn.jpg"
twitter_share_image: "images/marshablackburn.jpg"
tweet: "Exposed: @MarshaBlackburn is a fake conservative who loves online censorship. Real conservatives should vote her out!"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
