title: ' Loves Censorship'
share_title: ' is a fake conservative who loves Internet censorship'
share_description: "'s taken hundreds of thousands from big media companies to sell us out."
tweet:
  prefix: 'Exposed: '
  postfix: ' is a fake conservative who hates free speech and loves online censorship and surveillance'

author:
  twitter: fightfortheftr
  twitter_id: 382376904

# Build settings
markdown: kramdown
permalink: /:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
